# See: https://dart.dev/tools/pub/pubspec
name: model_viewer_example
description: >-
  Demonstrates how to use the ModelViewer widget.
homepage: https://github.com/drydart/model_viewer.dart/tree/master/example
repository: https://github.com/drydart/model_viewer.dart
issue_tracker: https://github.com/drydart/model_viewer.dart/issues
dependencies:
  flutter:
    sdk: flutter
  model_viewer:
    path: ../
  cupertino_icons: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.8.1 <3.0.0'
flutter:
  uses-material-design: true
  assets:
    - etc/assets/Astronaut.glb
publish_to: none
