# See: https://dart.dev/tools/pub/pubspec
name: model_viewer
version: 0.8.0
description: >-
  A Flutter widget for rendering interactive 3D models in the glTF and GLB
  formats.
homepage: https://github.com/drydart/model_viewer.dart
repository: https://github.com/drydart/model_viewer.dart
issue_tracker: https://github.com/drydart/model_viewer.dart/issues
documentation:
dependencies:
  flutter:
    sdk: flutter
  dogma: ^0.0.1
  flutter_android: ^0.8.0
  webview_flutter: ^0.3.22
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
dependency_overrides:
environment:
  sdk: '>=2.8.1 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'
flutter:
  assets:
    - etc/assets/template.html
    - etc/assets/model-viewer.js
